### ISSUE TITLE
Toggle logging in channel

### ISSUE THREAD

**Issue by Anonymoose100** [Blackcatmaxy/Botcatmaxy#155] opened 2022-05-06 02:27 UTC
1. would look like _!editinfraction (UserID) (infraction number) [new infraction reason]_. right now, you have to remove the warn then reapply it which is awkward. ive seen unbelievaboat use this feature, but idk if it can work with this bot so sorry for suggesting it if its not possible
2. would look like _!logs togglelogchannel (edit/delete, leave blank for neither)_ or so, idk, would help for staff/admin only channels

sorry if these were already suggested and replied to, im new to using this bot and made this account to suggest these features

**Comment by Blackcatmaxy** [comment] 2022-05-06 02:57
Number one is a duplicate of #61 

I know ``!dmhelp`` is a bit unwieldy right now (fix is in testing) but it shows these two commands for point 2
``!logs togglelogdeleted``
Toggles if deleted messages should be logged.
Useable in guilds only
Requires administrator permission
``!logs togglelogedited``
Toggles if edited messages should be logged.
Useable in guilds only
Requires administrator permission

Thank you for your time suggesting but please in the future please check for existing issues and separate your suggestions into discrete issues.

**Comment by Blackcatmaxy** [comment] 2022-05-06 05:20
As has been pointed out to me the commands I mentioned are guild-wide not channel-wide.

**Comment by Blackcatmaxy** [comment] 2022-05-06 05:24
Alternate solution until this is implemented from @BeagleJonas on Discord as BotCatMaxy does not require the Administrator permission if all other permissions are granted as new ones are created by Discord.
> granted they could just not give BCM admin and make it so bcm cant view those channels

**Comment by clerically** [comment] 2022-05-06 05:43
Should the specified log channel automatically be added to the log blacklist (removable), or should this be left up to the server admins? (i.e., deleting a logged message in the log channel does **not** display a deleted message log for that channel)

**Comment by Blackcatmaxy** [comment] 2022-06-01 20:01
Closed in #156 and 1d190bd1f336e8911e84ffdf0fd286a73bcde5a0 adding channel blacklisting commands.

**Closed as completed by Blackcatmaxy** 2022-06-01 20:01 UTC
Labels: enhancement
