### ISSUE TITLE
Log bans in infraction log.

### ISSUE THREAD

**Issue by Reecemanw** [Blackcatmaxy/Botcatmaxy#162] opened 2022-11-03 12:16 UTC
When viewing a users infractions not being able to see bans on the list makes keeping track of a ban per x weight system quite hard. Having bans be displayed amongst the warns and what weight the user had when they were banned would be a tremendous help for moderating as to save fishing through ban logs to find if a user has already been banned for total weight or not.

**Comment by Blackcatmaxy** [comment] 2022-11-03 18:25
Duplicate of #99

**Closed as not planned by Blackcatmaxy** 2022-11-03 18:25 UTC
Labels: duplicate, enhancement
